# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Mmr2AqqCC9CUe93beZpQBh6wpwcui2tC31lQt2qckdfchDENoqeQ03bvlcA/AcBlrI+9PfHr7EkZXK3GtVG9UnRrH4lUd7URDdp5IZtV8t2A+NuI6If1eG8a5R1NDttFo//CimBxQ5VKeKj6dABMOFvQ1LjvGbnSvAQM0BhKsK2AcziDse+S2hlZaQfLM4JER1bbZb7h0RTfo58+vxo8E5FO6PQy6/eH+narcgMO/No9aU6ZD5YgnZrddLBr9YBDlqQAps4p57UKq7YdipWJJSaS9WkG7IrZXtRgPhfEncCFxTelkhUrj28qYAVv64jeHC189HHWRd2T8w/NdHVJoesOh/Llg/rl8bZKL4KP8VfsIc5cQv8qarENEEjZieUg5CSZ4IShQc84A9X1RzjZk5IWbKBdwrsUlr57q1An1D9U/vKdD/WUoNy/IzVJCUV1veqXN5XSRyT4jT5ow7Ye1gSYyxVOy7zwqSLAMHcdnQXBpqUQsMH6knxENAjyNc8vLYx5p/fyEWf798ZuyvyQT8SUtGbfUNf+H7S2/7/b4XHTq5jApAkcxa7E5xagM6TCfJ013iAWlZAu5rhbhlNJpASIb+RGJH4OZisDuwNbPUHN7LRqAzob57CEQ9cCAT3H/pMH+G0IuihYwcP2ORzwt480SE3fREdmvutk4l5eKA4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
