appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: l8jdgwhKcuPr/5BDVZpPMcsevUAcld3lUDFysDRoZhJCJEDgdAXEAXWOoDXe+LCiZBRdzLuCUfnFflIUhLzFWeBbLnKMjYX87Pz+1ACOkOdvvvs1oYZysrMpLJqx5pFa19g3xjR0TTBm7Y/QFqM3fdjaqvqI0qOM7X1WlRJpWbbwUhU1lTiuk2DpUf8CqYQIpRi4jH2VLEh1gknPKweNp+g3mQxvNPcgFroZUeMfSNEOBis9rjQU3IYOS8HMdq/6n1E4zZE6CG4DBL5IDc1S/aoRP8CR49wQ/4P4ElhvSC6BlAlq6B0dHuuDa/5Cj5P9Fr7qgXWLpd1yhFvkYNFj/Eb7uXDzW/5/G7m8go4BzRAymjzyCBCnHt0aj7EzvRNE/1g1bpbBMswX+1HvWDH8d5dEGF2MXuyBZM10EcjeigjtuC3HVJLo02qCqcdyf9M412pOp4zScKHJ9dbd/fsAKsA+nlPrv2vzIGyShaEKlp3O5VWe1UV/OPRYsy3FvWKmtEvuczjg3t+BKbjk2GPKHpVHSLfSvsywNkD2ZWkUGPuplcMH8yrmfhjyRO/ICkkW+ff7Xu3Y930R3znIsPuYVvIYpLc7XVc+ASNjloLKUTd9cUffeM9m0NJ5AviseyBEYyjR34aD7rbM/tgjXGqb1FsXGEUbbun8asDngzO/5N4=}
bot:
  automerge: true
