travis:
  secure:
    BINSTAR_TOKEN: Mmr2AqqCC9CUe93beZpQBh6wpwcui2tC31lQt2qckdfchDENoqeQ03bvlcA/AcBlrI+9PfHr7EkZXK3GtVG9UnRrH4lUd7URDdp5IZtV8t2A+NuI6If1eG8a5R1NDttFo//CimBxQ5VKeKj6dABMOFvQ1LjvGbnSvAQM0BhKsK2AcziDse+S2hlZaQfLM4JER1bbZb7h0RTfo58+vxo8E5FO6PQy6/eH+narcgMO/No9aU6ZD5YgnZrddLBr9YBDlqQAps4p57UKq7YdipWJJSaS9WkG7IrZXtRgPhfEncCFxTelkhUrj28qYAVv64jeHC189HHWRd2T8w/NdHVJoesOh/Llg/rl8bZKL4KP8VfsIc5cQv8qarENEEjZieUg5CSZ4IShQc84A9X1RzjZk5IWbKBdwrsUlr57q1An1D9U/vKdD/WUoNy/IzVJCUV1veqXN5XSRyT4jT5ow7Ye1gSYyxVOy7zwqSLAMHcdnQXBpqUQsMH6knxENAjyNc8vLYx5p/fyEWf798ZuyvyQT8SUtGbfUNf+H7S2/7/b4XHTq5jApAkcxa7E5xagM6TCfJ013iAWlZAu5rhbhlNJpASIb+RGJH4OZisDuwNbPUHN7LRqAzob57CEQ9cCAT3H/pMH+G0IuihYwcP2ORzwt480SE3fREdmvutk4l5eKA4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
